// app/layout.js
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import AuthProvider from '@/components/AuthProvider'
import AuthStatus from '@/components/AuthStatus'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'trungtienlearn NextJS', // Tiêu đề mặc định cho trang web
  description: 'Generated by create next app, customized by Me!',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        {/* Header đơn giản */}
        <Header />
        {/* Nội dung chính của trang */}
        <main className="flex-grow container mx-auto p-4">
          {children}
        </main>

        {/* Footer đơn giản */}
        <footer className="bg-gray-200 text-center p-4 mt-auto">
          <p className='text-gray-700'>&copy; 2025 [trungtienlearn.com] All rights reserved.</p>
          {/* Lưu ý: Sửa năm thành năm hiện tại nếu cần */}
        </footer>
      </body>
      </AuthProvider>
    </html>
  )
}