// app/layout.js
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Awesome Blog', // Tiêu đề mặc định cho trang web
  description: 'Generated by create next app, customized by Me!',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        {/* Header đơn giản */}
        <header className="bg-gray-800 text-white p-4">
          <div className="container mx-auto">
            <h1 className="text-xl font-bold"><Link href='/'>My Awesome Blog</Link></h1>
            {/* Có thể thêm Navigation Links ở đây sau */}
          </div>
        </header>

        {/* Nội dung chính của trang */}
        <main className="flex-grow container mx-auto p-4">
          {children}
        </main>

        {/* Footer đơn giản */}
        <footer className="bg-gray-200 text-center p-4 mt-auto">
          <p className='text-gray-700'>&copy; 2025 My Awesome Blog. All rights reserved.</p>
          {/* Lưu ý: Sửa năm thành năm hiện tại nếu cần */}
        </footer>
      </body>
    </html>
  )
}